### ISSUE TITLE
Give lesson notebooks descriptive names

### ISSUE THREAD

**Issue by mdpiper** [CodeToCommunicate/CoCoLessons#16]
If we use descriptive names it should help students and instructors know what's covered in a notebook at a glance.

**Comment by mdpiper** [comment]
In https://github.com/CodeToCommunicate/CoCoTerm1/pull/15#issuecomment-1010203406, @aguspesce suggested:

> notebook_1_ intro
> notebook_2_ Matplotlib
> notebook_3_ more_python
> notebook_4_ pandas

**Comment by mdpiper** [comment]
Here's my try, building on @aguspesce's idea above:

> coco_1_coding_environment (this will be a directory with Markdown files)
> coco_2_python_basics
> coco_3_matplotlib
> coco_4_functions_and_more (it rhymes!)
> coco_5_pandas

**Comment by mdpiper** [comment]
@aguspesce @isamarcortes Bumping this up. Do you have any thoughts on this?

**Comment by aguspesce** [comment]
@mdpiper I like your idea!

**Comment by isamarcortes** [comment]
Oh I like this a lot!!! Thanks @mdpiper

**Comment by mdpiper** [comment]
I ran into a problem. Because GitHub lists directories before files, the first lesson isn't listed next to the others, which I don't think looks good.

<img width="1186" alt="Screen Shot 2022-01-17 at 3 13 40 PM" src="https://user-images.githubusercontent.com/5673711/149842662-e34afc70-1798-484e-abcf-cd6da6aed0a1.png">

I think what I'll do to solve this is combine the Markdown files in the lesson 1 directory into a single file & remove the directory.
